# Generated by Django 3.2 on 2023-09-25 11:13

import apps.products.models
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('media', '0001_initial'),
        ('categories', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('product_id', models.TextField(blank=True, null=True)),
                ('part_type', models.TextField(blank=True, null=True)),
                ('bkpp_p_n', models.TextField(blank=True, null=True)),
                ('publish', models.BooleanField(default=False)),
                ('year_1967', models.BooleanField(blank=True, null=True)),
                ('year_1968', models.BooleanField(blank=True, null=True)),
                ('year_1969', models.BooleanField(blank=True, null=True)),
                ('name', models.TextField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('gm_part_numbers', models.TextField(blank=True, null=True)),
                ('aim_numbers', models.TextField(blank=True, null=True)),
                ('years', models.TextField(blank=True, null=True)),
                ('body_style', models.TextField(blank=True, null=True)),
                ('trim', models.TextField(blank=True, null=True)),
                ('interior', models.TextField(blank=True, null=True)),
                ('engine', models.TextField(blank=True, null=True)),
                ('transmission', models.TextField(blank=True, null=True)),
                ('part_manufacturer', models.TextField(blank=True, null=True)),
                ('manufacturer_part_name', models.TextField(blank=True, null=True)),
                ('manufacturer_part_number', models.TextField(blank=True, null=True)),
                ('suppliers_name', models.TextField(blank=True, null=True)),
                ('suppliers_part_name', models.TextField(blank=True, null=True)),
                ('suppliers_part_number', models.TextField(blank=True, null=True)),
                ('email_to_tim', models.BooleanField(default=False)),
                ('email_address', models.EmailField(blank=True, max_length=254, null=True)),
                ('customer_number', models.TextField(blank=True, null=True)),
                ('street_address', models.TextField(blank=True, null=True)),
                ('city_state_zip', models.TextField(blank=True, null=True)),
                ('quantity_included', models.PositiveIntegerField(blank=True, null=True)),
                ('quantity_needed', models.PositiveIntegerField(blank=True, null=True)),
                ('to_whom', models.TextField(blank=True, null=True)),
                ('cost', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('msrp', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('unit_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('unit_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('photo_p_n', models.TextField(blank=True, null=True)),
                ('fixed_shipping', models.BooleanField(default=False)),
                ('multiple_fixed_shipping', models.BooleanField(default=False)),
                ('inventory', models.PositiveIntegerField(default=0)),
                ('gm_affiliation', models.TextField(blank=True, null=True)),
                ('remanufactured', models.BooleanField(default=False)),
                ('made_in_the_usa', models.BooleanField(default=False)),
                ('sold_as', models.TextField(blank=True, null=True)),
                ('shipping_method', models.TextField(blank=True, null=True)),
                ('help', models.TextField(blank=True, null=True)),
                ('special_handling', models.TextField(blank=True, null=True)),
                ('h', models.TextField(blank=True, null=True)),
                ('l', models.TextField(blank=True, null=True)),
                ('w', models.TextField(blank=True, null=True)),
                ('weight', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('sku', models.CharField(db_index=True, max_length=8)),
                ('new', models.BooleanField(default=False)),
                ('onSale', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(db_column='category', on_delete=django.db.models.deletion.CASCADE, to='categories.category')),
                ('images', models.ManyToManyField(related_name='products', to='media.Image')),
            ],
            options={
                'verbose_name': 'Product',
                'verbose_name_plural': 'Products',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='Variant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, choices=[('Color', 'Color'), ('Size', 'Size')], max_length=9)),
                ('value', models.CharField(max_length=50, unique=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('images', models.ImageField(blank=True, upload_to=apps.products.models.variants_directory_path)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variant', to='products.product')),
            ],
        ),
    ]
