# Generated by Django 3.2 on 2023-09-26 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='classic_industries',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='npw',
            field=models.BooleanField(default=False),
        ),
    ]
