# Generated by Django 3.2 on 2023-09-26 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_auto_20230926_1737'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='contact_email',
            field=models.EmailField(max_length=255),
        ),
    ]
